language: ruby
notifications:
  email:
    on_success: change
    on_failure: always
before_install:
- gem update --system $RUBYGEMS_VERSION
- gem --version
- gem install bundler
- bundle --version
bundler_args: --binstubs
script: bin/rake test
rvm:
- 1.9.2
- 1.9.3
- 2.0.0
- 2.1.0
- rbx
- 1.8.7
- jruby-18mode
- jruby-19mode
- jruby-head
- ruby-head
matrix:
  allow_failures:
    - rvm: 1.8.7
    - rvm: jruby-18mode
    - rvm: jruby-19mode
    - rvm: jruby-head
    - rvm: ruby-head
