language: ruby
notifications:
  email:
    on_success: change
    on_failure: always
before_install:
- gem update --system $RUBYGEMS_VERSION
- gem --version
- gem install bundler
- bundle --version
bundler_args: --binstubs
script: rvmsudo_secure_path=1 rvmsudo EXCLUDE=$EXCLUDE bin/rake test
rvm:
- 1.9.2
- 1.9.3
- 2.0.0
- 2.1.0
- ruby-head
matrix:
  include:
    # https://jira.codehaus.org/browse/JRUBY-5897 - jruby doesn't support raw sockets
    # jruby timeout doesn't work with udp sockets
    # jruby: tcp tests failing with Errno::ECONNREFUSED to localhost port 22
    - rvm: jruby-head
      env: TESTOPTS=-v EXCLUDE=udp,icmp,tcp
    - rvm: rbx
      env: EXCLUDE=icmp
  allow_failures:
    - rvm: rbx
    - rvm: jruby-head
    - rvm: ruby-head
